# Generated by Django 2.0.13 on 2019-09-10 09:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], max_length=10)),
                ('link', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=50)),
                ('assinged_to', models.CharField(choices=[('MADHU', 'MADHU'), ('JAGADEESH', 'JAGADEESH'), ('PRABHU', 'PRABHU')], max_length=10)),
                ('history', models.CharField(max_length=20)),
                ('created_by', models.CharField(choices=[('MADHU', 'MADHU'), ('JAGADEESH', 'JAGADEESH'), ('PRABHU', 'PRABHU')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.user')),
            ],
        ),
    ]
