# Generated by Django 2.0.13 on 2019-09-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20190910_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assinged_to',
            field=models.CharField(choices=[('MADHU', 'MADHU'), ('JAGADEESH', 'JAGADEESH'), ('PRABHU', 'PRABHU')], max_length=10),
        ),
    ]
